### ISSUE TITLE
Mockup main layout

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#10]
![Captura de Pantalla 2019-06-09 a la(s) 19 27 08](https://user-images.githubusercontent.com/6130385/59166209-9f3cfd00-8aec-11e9-80ea-36c87dbe4a05.png)
We need to have the main layout. The main layout contains the navbar (or sidebar), the footer, and the section were all the routes will show dynamic data. See image attached in this issue to based on it. Attach the mockup as image.

**Comment by Inatedy** [comment]
![Main-layout](https://user-images.githubusercontent.com/46948948/59560041-7d51e780-8fd0-11e9-9d1a-62b74b18d699.png)
![Main-layout – 1](https://user-images.githubusercontent.com/46948948/59560042-7d51e780-8fd0-11e9-9e8e-f43ec6777916.png)

**Comment by MartinMelo97** [comment]
I like it. But you'll need to do it again, using the sidebar, and the footer select. The "¿Qué desea hacer" options it's a little repetitive because the user always have quickly access to all the modules in the sidebar. Instead of this, i'll prefer a Dashboard. But the main goal of this issue is to see the sidebar, the footer and the space where all the info has been.

**Comment by Inatedy** [comment]
what links do you need to be in there?

**Comment by Inatedy** [comment]
@MartinMelo97 what links do you need to be in there?
