### ISSUE TITLE
Login Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#12]
Create the mockup of the login that will be the only screen available when the user is not logged in.
In this mockup we need the following:

**Title** "Iniciar sesión"
**Input** (placeholder = Usuario)
**Input** (placeholder = Contraseña) (type = password)
**Button** Iniciar sesión
**Label** ¿Olvidaste tu contraseña?

Using the reusable inputs, button and text type.

Attach the mockup in an image.

**Comment by Inatedy** [comment]
![login](https://user-images.githubusercontent.com/46948948/59560125-fc93eb00-8fd1-11e9-8b00-1fe651d74520.png)

**Comment by MartinMelo97** [comment]
I liked it a lot! Only the button text must be "Iniciar sesión". Otherwise, it's perfect.
