### ISSUE TITLE
Mockup Forgot Password Screen

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#13]
When some user of the project forgot his password, we need to redirect it to this screen.

**Title** Recupera tu contraseña
**Desc** ¿No recuerdas cuál es tu contraseña? No te preocupes. Ingresa el correo electrónico que tienes ligado a tu cuenta y en unos minutos recibirás un correo electrónico con los pasos necesarios para que puedas recuperarla ;)
**Input** (placeholder = user@domain.com)
**Button** Recuperar contraseña
**Label** ¿La recordaste? Inicia sesión 

Attach the mockup in an image

**Comment by Inatedy** [comment]
![forgot-password](https://user-images.githubusercontent.com/46948948/59560250-775e0580-8fd4-11e9-8dce-b588ee468463.png)

**Comment by MartinMelo97** [comment]
Great
