### ISSUE TITLE
List Reusable Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#15]
We need to make a list reusable for the list view for all the models. For example, in Notaria we use the Ant Design Table. Maybe we will use again the Tables. Check in Ant Design docs if there is better way to show the list items. In some modules as product maybe it's better work with cards (only if the products will have images). You'll decide about this.
Attach the mockup as an image

**Comment by Inatedy** [comment]
Employee
![LISTVIEW-EMPLOYEE](https://user-images.githubusercontent.com/46948948/59566009-a6e62f80-901f-11e9-9a4f-612d139e7a93.png)

**Comment by Inatedy** [comment]
Empleados
![LISTVIEW-EMPLOYEE](https://user-images.githubusercontent.com/46948948/59566043-207e1d80-9020-11e9-844e-2148278e3b0c.png)

**Comment by Inatedy** [comment]
CLIENTES
![LISTVIEW-EMPLOYEE](https://user-images.githubusercontent.com/46948948/59566091-c29e0580-9020-11e9-9105-a0a13362e484.png)

A mi se me hace un buen hábito que los jefes y empleados conozcan ya sea en caso de los jefes a sus empleados y los empleados a sus clientes, pero en la manera laborar y administrativa es más cómodo ver una lista solo con los nombres y algunos datos, por favor si se desea que empleados y clientes estén en lista en tabla dímelo y hago el mockup

**Comment by Inatedy** [comment]
A mi se me hace un buen hábito que los jefes y empleados conozcan ya sea en caso de los jefes a sus empleados y los empleados a sus clientes, pero en la manera laborar y administrativa es más cómodo ver una lista solo con los nombres y algunos datos, por favor si se desea que empleados y clientes estén en lista en tabla dímelo y hago el mockup

**Comment by Inatedy** [comment]
clientes y empleados
![LISTVIEW-CLIENTES – 1](https://user-images.githubusercontent.com/46948948/59566160-b8c8d200-9021-11e9-8cf8-c091cfb590c4.png)
![LISTVIEW-EMPLOYEE](https://user-images.githubusercontent.com/46948948/59566161-b8c8d200-9021-11e9-853f-d38b3ff70bf3.png)

**Comment by MartinMelo97** [comment]
Your mockup it's great. But i agree with you, in the case of Empleados and Clients, i prefer a table or a list with the info about this models. We need to remember that the could filter searching by name, or using a order by asc or desc.

**Comment by Inatedy** [comment]
mochups only of employees
![Uploading LISTVIEW-EMPLOYEE – 1.png…]()
![LISTVIEW-EMPLOYEE – 2](https://user-images.githubusercontent.com/46948948/59694163-cd39d580-91ad-11e9-979a-832a84e2cdef.png)
![LISTVIEW-EMPLOYEE – 3](https://user-images.githubusercontent.com/46948948/59694188-d4f97a00-91ad-11e9-9cef-f066f30e29a6.png)

**Comment by Inatedy** [comment]
![LISTVIEW-EMPLOYEE – 1](https://user-images.githubusercontent.com/46948948/59711145-2b77b000-91d0-11e9-997c-672afd7a41cb.png)

**Comment by MartinMelo97** [comment]
GREAT! I like it, only two things, when you filter and order by, you put the values ("Primera actualización, "Desc"). I like to see its values as a tag. It mean. with a different background color and color. Maybe it look great with background color and black text color.

And the search icon looks great, but i think that could be better put an input and inside this input, put the search icon. What do you think?

**Comment by Inatedy** [comment]
![LISTVIEW-EMPLOYEE – 2](https://user-images.githubusercontent.com/46948948/59712335-9fb35300-91d2-11e9-983c-d67720d9304c.png)
![LISTVIEW-EMPLOYEE – 3](https://user-images.githubusercontent.com/46948948/59712337-a04be980-91d2-11e9-911b-f1a6a0148e2c.png)
![LISTVIEW-EMPLOYEE – 1](https://user-images.githubusercontent.com/46948948/59712339-a04be980-91d2-11e9-926d-1e0a50d7bd5f.png)

**Comment by Inatedy** [comment]
clientes
![LISTVIEW-clients – 4](https://user-images.githubusercontent.com/46948948/59713337-d0948780-91d4-11e9-9971-38f7daf18a21.png)

**Comment by Inatedy** [comment]
Clientes
![LISTVIEW-clients – 4](https://user-images.githubusercontent.com/46948948/59713418-118c9c00-91d5-11e9-9070-4ab30a16a66d.png)

**Comment by Inatedy** [comment]
![LISTVIEW-products – 4](https://user-images.githubusercontent.com/46948948/59734205-16be0b00-9216-11e9-85b5-6dcd20cbfc81.png)

**Comment by Inatedy** [comment]
![LISTVIEW-servicios – 5](https://user-images.githubusercontent.com/46948948/59734941-13784e80-9219-11e9-975b-6e3440ffb525.png)

**Comment by Inatedy** [comment]
![LISTVIEW-works – 6](https://user-images.githubusercontent.com/46948948/59778118-80243500-927b-11e9-8daf-490e365a9c24.png)
trabajos

**Comment by MartinMelo97** [comment]
@Inatedy Remember that the IdServicio and the IdClient are Foreign Keys in the Database. So, instead of have only the Id in the table, we need to know the name of the service, and the client, pls

**Comment by Inatedy** [comment]
Corrección del de nombre en vez de id
![LISTVIEW-works – 6](https://user-images.githubusercontent.com/46948948/59856790-39970f00-933d-11e9-81f6-ba0c7ac09fea.png)

**Comment by Inatedy** [comment]
![LISTVIEW-EMPLOYEE – 3](https://user-images.githubusercontent.com/46948948/59858037-cba01700-933f-11e9-94f1-a17ae19dd166.png)
buscador y tags del filtro

**Comment by MartinMelo97** [comment]
Great
