### ISSUE TITLE
Detail Reusable Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#16]
As the list reusable mockup, we'll do the same with the Detail Mockups. In this case it will be a very basic structure, because each one of the models have different data to show, as images. In the detail the admin need to see not only the attribute of this model, it also need to be the info about the related tables (You can see the relationships in the Docs Folder in a file called DB Structure. But for now I'm only need the basic mockup of the detail view, such as, ok, this info will be here, and the info related will be on top or down, and using a table, or a list, or a cards. If you have any question about this, feel free to post that as a comment.

Attach

**Comment by Inatedy** [comment]
Muy básico pero fácil de entender 
![LISTVIEW-works – 7](https://user-images.githubusercontent.com/46948948/59803050-fd699d00-92af-11e9-99a5-ed804098a52f.png)

**Comment by MartinMelo97** [comment]
It looks good, some details:

- On Service and Cliente add a underline because here Will be the link to the detail of each one.
- And here, i like a list with the payment done. For example, the first payment was for $2000 and the second for $300

**Comment by Inatedy** [comment]
![LISTVIEW-works – 8](https://user-images.githubusercontent.com/46948948/59806717-014eec80-92bb-11e9-8015-df3c76621a32.png)
![LISTVIEW-works – 7](https://user-images.githubusercontent.com/46948948/59806718-014eec80-92bb-11e9-9cd2-039c382f960b.png)
@MartinMelo97  Así?

**Comment by MartinMelo97** [comment]
Mmmm, it look good, but if we show it as a droptown, it could be a little confuse. Maybe we need to show the payment history below the detail info.
