### ISSUE TITLE
Create Form Reusable Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#17]
When we create or edited some model we need a form, frecuently the same form is used for both, create and edited, only when its an edited action, the fields are prefilled with the actual data. Each one of the module has different data required to send to the backend. So in this task you'll need to define the width of each input (search for grid in ant design) And make an example. This will be the base for all the created and/or edited components in the frontend, the only thing that change will be the inputs.

**Comment by Inatedy** [comment]
![form](https://user-images.githubusercontent.com/46948948/59869121-33faf280-9358-11e9-8f07-462705c7392c.png)

**Comment by Inatedy** [comment]
![form](https://user-images.githubusercontent.com/46948948/59869172-5260ee00-9358-11e9-8c99-d9b11c8c73c0.png)

**Comment by MartinMelo97** [comment]
We need to Id make disabled to avoid the user can edit that Id. on Quantity the input needs to be number. And the created doesn't be shower in the form.

**Comment by Inatedy** [comment]
![form](https://user-images.githubusercontent.com/46948948/59879162-b2af5a00-936f-11e9-8b3b-b8fe21196ec3.png)

**Comment by MartinMelo97** [comment]
Hmm, I could like an another items order
