### ISSUE TITLE
Define Colors for the Project

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#2]
We need to define the colors used in the project, based on the logo colors (available in the Design Folder in Drive). We need to define the primary, accent (secondary), third, black & white colors. For the documentation of this colors, we need to create a Google Doc into the "Design" folder in Drive and set the colors with its hexadecimal code.

**Comment by MartinMelo97** [comment]
@Inatedy What's means the p-light and the p-dark into the primary color?
In the accent color it could be any of the three options?

**Comment by Inatedy** [comment]
@MartinMelo97  en la documentación de _material design_ encontre que se podían trabajar con dos versiones del color primario por si se necesitaban. it´s mean primary-light and dark

**Comment by MartinMelo97** [comment]
Ah ok ok, perfect

**Comment by Inatedy** [comment]
it´s ok the dark version? or in white?
