### ISSUE TITLE
Define fonts

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#4]
We need to define the fonts to use and the size, weight and decorations for the diferent types of text in the project. For the fonts, I should recommend use Google Fonts to pick at most 3 font type. We need to define the color (using the colors defined in the Issue #2) size, weight, and decoration if the type requires for the following text types:

- Header
- Title
- Subtitle
- Description
- Button texts
- Input texts.

Document this into a Design folder in Drive, creating a Google Doc with the title "Fonts Gosen Project"

**Comment by MartinMelo97** [comment]
@Inatedy Roboto is the default font for any project in React (creo) hahaha, but it's ok

**Comment by Inatedy** [comment]
yes, it is. I was reading for the best fonts for a mobile project, and that´s why I chose that font, I also found   Montserrat. What do u think about Montserrat? it´s also easy for the view
