### ISSUE TITLE
Create Mocku for Form Password Reset

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#47]
We are missing the mockup when the user receive the email, and he needs to put it new password and confirm that password.

The forms needs to Password Inputs and a Button to handle the action.

**Comment by Inatedy** [comment]
@MartinMelo97  hey! will you give me the exact title and caption of the button?

**Comment by Inatedy** [comment]
Maybe in the mockup will be.... "Confirmar contraseña" or 
"RECUPERA TU CONTRASEÑA
                Confirma tu contraseña" o  lo decido yo?

**Comment by MartinMelo97** [comment]
Title: Crea tu nueva contraseña

Input 1: Nueva contraseña
Input 2: Confirma tu nueva contraseña

Button: Guardar

**Comment by Inatedy** [comment]
Gracias!

**Comment by Inatedy** [comment]
![confirm-password](https://user-images.githubusercontent.com/46948948/60377634-458a6d00-99de-11e9-82c1-90bbe97ae6cd.png)

**Comment by MartinMelo97** [comment]
In the title is "Crea tu nueva contraseña". The rest it's ok. Chance the title pls, upload tue Mockup to Drive and talk with Isaac to start with they UI component

**Comment by Inatedy** [comment]
Sorry sorry i got it

**Comment by Inatedy** [comment]
![confirm-password](https://user-images.githubusercontent.com/46948948/60377755-eaa54580-99de-11e9-8ce8-3615c13ff500.png)

**Comment by Inatedy** [comment]
ya esta en drive

**Comment by MartinMelo97** [comment]
Thanks @Inatedy, @IsaacGarHer go ahead.
