### ISSUE TITLE
Create Mockup for the buttons of the project

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#5]
We need to create mockups for each button that we use on the project. Put special attention to the width size (on percentage), border radius, shadows, border size, color, etc. For the moment, create the following buttons.

- Main button (When it's the only option, or when we have two or more options, but this is the principal)
- Secondary button (When we have two or more options to be clickable, this is the second in the priority).

To document this, attach into this issue a .jpeg or .png image about both buttons.

**Comment by Inatedy** [comment]
En drive hay un documento llamado buttons donde describo algunos detalles, como los colores, y shadows

![BOTON-PRIMARIO-1 1](https://user-images.githubusercontent.com/46948948/59392669-1917f500-8d3e-11e9-8503-715c0d885f51.png)
![BOTON-SECUNDARIO-1 1](https://user-images.githubusercontent.com/46948948/59392670-1917f500-8d3e-11e9-8c27-0c6333bde84b.png)
![BOTON-SECUNDARIO-1 2](https://user-images.githubusercontent.com/46948948/59392671-19b08b80-8d3e-11e9-9666-5a851e700213.png)
![BOTON-SECUNDARIO-2 1](https://user-images.githubusercontent.com/46948948/59392672-19b08b80-8d3e-11e9-873a-e5ab9d4db80d.png)
![BOTON-TERCIARIO-1 1](https://user-images.githubusercontent.com/46948948/59392673-19b08b80-8d3e-11e9-9701-15d4be546312.png)
![BOTON-TERCIARIO-1 2](https://user-images.githubusercontent.com/46948948/59392674-19b08b80-8d3e-11e9-87da-27a02c409837.png)
![BOTON-PRIMARIO-1 1 – 1](https://user-images.githubusercontent.com/46948948/59392675-1a492200-8d3e-11e9-88ab-0708312b7267.png)

**Comment by MartinMelo97** [comment]
@Inatedy Tomorroy we'll decide the 3 buttons in a meeting.

**Comment by Inatedy** [comment]
Well.

**Comment by MartinMelo97** [comment]
Main Button -> https://user-images.githubusercontent.com/46948948/59392669-1917f500-8d3e-11e9-8503-715c0d885f51.png

Main Button Outlined -> https://user-images.githubusercontent.com/46948948/59392674-19b08b80-8d3e-11e9-87da-27a02c409837.png


Secondary button -> https://user-images.githubusercontent.com/46948948/59392670-1917f500-8d3e-11e9-8c27-0c6333bde84b.png

Secondary button Outlined -> 

Third button -> https://user-images.githubusercontent.com/46948948/59392673-19b08b80-8d3e-11e9-9701-15d4be546312.png

**Comment by Inatedy** [comment]
@MartinMelo97  Secondary button Outlined -> Do I make a new mockup?

**Comment by MartinMelo97** [comment]
@Inatedy Yes check in Ant Design the difference between a natural button and a outlined button and based on it, try to make a new mockup for the secondary button but outlined

**Comment by Inatedy** [comment]
@MartinMelo97  Va lo checo

**Comment by Inatedy** [comment]
![BOTON-SECUNDARIO-1 – 1](https://user-images.githubusercontent.com/46948948/59646242-ad69c980-913b-11e9-9cee-f83506f58fd9.png)
 boton secundario outline

**Comment by Inatedy** [comment]
![BOTON-SECUNDARIO-1 – 1](https://user-images.githubusercontent.com/46948948/59646332-2701b780-913c-11e9-977e-e7e164874b23.png)

**Comment by MartinMelo97** [comment]
Secondary https://user-images.githubusercontent.com/46948948/59646332-2701b780-913c-11e9-977e-e7e164874b23.png

**Comment by MartinMelo97** [comment]
Add it to Drive pls
