### ISSUE TITLE
Admin Dashboard Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#50]
We need to create a Dashboard to the Admin User where they can see important info about all. We need to show a summary of each models. For example:

Model: Employeee
Total: 15 (Total of employees)
Último empleado contratado: El Yesos
Empleado con más trabajos: El Melo

It could be cards, you can search in Dribbble for a little inspiration

**Comment by Inatedy** [comment]
![Web 1920 – 4](https://user-images.githubusercontent.com/46948948/60853764-27cdbc80-a1c3-11e9-9594-4e98df7f0cc7.png)

![Web 1920 – 2](https://user-images.githubusercontent.com/46948948/60853765-28665300-a1c3-11e9-944c-b7ba55976236.png)

**Comment by MartinMelo97** [comment]
@Inatedy Hmm, I think that the yellow as background color of the sidebar doesn't like me. Maybe try with another yellow option or change the colors. Y like the dashboard, but maybe it could be great if each module (Contabilidad, Empleados, etc) has a icon. And also make the color contrast between the background and the card of the module increase. Because i cannot difference between the background and each card :D

**Comment by Inatedy** [comment]
![Web 1920 – 4](https://user-images.githubusercontent.com/46948948/60853934-d540d000-a1c3-11e9-8ba9-18e1f0f4f70d.png)

![Web 1920 – 2](https://user-images.githubusercontent.com/46948948/60853935-d5d96680-a1c3-11e9-85e7-4ec88634d2d5.png)

**Comment by MartinMelo97** [comment]
It's any change? @Inatedy

**Comment by Inatedy** [comment]
jejeje lo siento acabo de ver el comentario xd

**Comment by Inatedy** [comment]
Corrección
![Web 1920 – 5](https://user-images.githubusercontent.com/46948948/60924510-045c4d80-a267-11e9-9246-684a340e3bfe.png)
![Web 1920 – 6](https://user-images.githubusercontent.com/46948948/60924511-045c4d80-a267-11e9-8a76-13d30eba2578.png)

Los iconos que agregue aquí no son, son los iconos que estan en la side bar, solo que no los encontre xc y no los tengo en color blanco xc

**Comment by MartinMelo97** [comment]
It's ok @Inatedy, we're going to approve this mockup. If the client wants some change we're going to refactor that. Please, upload it to the mockups folder on Drive.
