### ISSUE TITLE
Admin Profile Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#52]
We need to have a Profile Mockup where the user can see it's personal information and the links to edit that information. The admin info saved in the DB are: 

First Name (Nombre)
Last Name (Apellidos)
Username (Nombre de usuario)
Email
Phone number (Número de teléfono)
Gender (Género)
Birth Date (Fecha de nacimiento)
Street (Calle)
City (Ciudad)
State (Estado)
Country (País)
ZIP (Código Postal)

**Comment by Inatedy** [comment]
va a llevar foto? xd

**Comment by Inatedy** [comment]
![LISTVIEW-works – 8](https://user-images.githubusercontent.com/46948948/60934884-8a8b8a80-a28d-11e9-87a3-2e39134fbc1c.png)
![LISTVIEW-works – 9](https://user-images.githubusercontent.com/46948948/60934885-8a8b8a80-a28d-11e9-8703-794e084e4547.png)

**Comment by Inatedy** [comment]
![LISTVIEW-works – 11](https://user-images.githubusercontent.com/46948948/60940605-aef16200-a2a1-11e9-9b70-6695b332f76b.png)

**Comment by Inatedy** [comment]
![LISTVIEW-works – 14](https://user-images.githubusercontent.com/46948948/60941119-89655800-a2a3-11e9-9a58-c1a659337362.png)
versión 3

**Comment by Inatedy** [comment]
![LISTVIEW-works – 14](https://user-images.githubusercontent.com/46948948/60942304-c0d60380-a2a7-11e9-84d1-72b18a630fbb.png)

en estos ya cambie el color de fondo a #1D1C1C

**Comment by Inatedy** [comment]
en estos ya cambie el color de fondo a #1D1C1C
![LISTVIEW-works – 8](https://user-images.githubusercontent.com/46948948/60942335-e400b300-a2a7-11e9-84b9-795c440e1195.png)
![Uploading LISTVIEW-works – 11.png…]()
![Uploading LISTVIEW-works – 14.png…]()

**Comment by Inatedy** [comment]
en estos ya cambie el color de fondo a #1D1C1C
![LISTVIEW-works – 8](https://user-images.githubusercontent.com/46948948/60942389-127e8e00-a2a8-11e9-892d-5c82501b8a99.png)
![LISTVIEW-works – 11](https://user-images.githubusercontent.com/46948948/60942390-127e8e00-a2a8-11e9-8bc6-c7b3f482f3c1.png)
![LISTVIEW-works – 14](https://user-images.githubusercontent.com/46948948/60942391-127e8e00-a2a8-11e9-941a-e7c49156f46d.png)

**Comment by MartinMelo97** [comment]
I like the version 3. It looks pretty. Only the Editar option it has a bad UX. As a "call to action" component. He need to be on the top. Maybe between the username and the email It could be a great place.

**Comment by Inatedy** [comment]
![LISTVIEW-works – 14](https://user-images.githubusercontent.com/46948948/61090436-3e168b00-a404-11e9-8305-c94e52c1f681.png)
![LISTVIEW-works – 16](https://user-images.githubusercontent.com/46948948/61090439-3eaf2180-a404-11e9-87e8-92bf725d9f3a.png)
![LISTVIEW-works – 17](https://user-images.githubusercontent.com/46948948/61090440-3eaf2180-a404-11e9-869a-152c19ea5629.png)
![LISTVIEW-EMPLOYEE – 1](https://user-images.githubusercontent.com/46948948/61090441-3eaf2180-a404-11e9-9f61-cd9a31330430.png)

**Comment by MartinMelo97** [comment]
The last version, with the "Editar" like a button

**Comment by MartinMelo97** [comment]
It's approved.Upload it to Drive please

**Comment by Inatedy** [comment]
vale
