### ISSUE TITLE
Admin Edit Profile Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#53]
We need to build a form where the user can Edit it info.

The inputs and data entries contains in the form are:

First Name (Nombre) *input* REQUIRED
Last Name (Apellidos) *input* REQUIRED
Username (Nombre de usuario) *input* REQUIRED
Email *input* REQUIRED
Phone number (Número de teléfono) *numberInput* REQUIRED
Gender (Género) *Radio* REQUIRED
Birth Date *DatePicker* (Fecha de nacimiento) 
Street *Input* (Calle)
City *Input* (Ciudad)
State *Select* (Estado)
Country *Select* (País)
ZIP *Input* (Código Postal)

**Comment by Inatedy** [comment]
![LISTVIEW-works – 9](https://user-images.githubusercontent.com/46948948/60943292-237cce80-a2ab-11e9-874c-58c6f0556f1d.png)
 el color de fondo lo cambie a #1D1D1D

**Comment by MartinMelo97** [comment]
Y like that. Only we need to adjust this as the version 3 of the Admin Detail Mockup. Maybe you only need to change the button of the left and the profile photo on the right.

**Comment by Inatedy** [comment]
![admin-form](https://user-images.githubusercontent.com/46948948/61094320-52fb1a80-a414-11e9-967c-96fefc4d06b2.png)

**Comment by MartinMelo97** [comment]
As we are on Edit component. The "Edit" option doesn't appear here. And the "Guardar" and "Cancelar" buttons are the "Call to Action" elements. So put they on the bottom is not a bad idea, but we could try putting them in the place of "Editar" Button, remember that it will be removed. Could we try @Inatedy

**Comment by Inatedy** [comment]
![admin-form](https://user-images.githubusercontent.com/46948948/61095161-ec77fb80-a417-11e9-8dcf-cb813ea69329.png)
![admin-form – 1](https://user-images.githubusercontent.com/46948948/61095162-ec77fb80-a417-11e9-80c7-1fef9a72e050.png)
Sorry for the lapsus mensus xd

**Comment by MartinMelo97** [comment]
Oh, I forgot that the first name, the last name, the username and the photo profile could be editables

**Comment by MartinMelo97** [comment]
Can you check that, please

**Comment by Inatedy** [comment]
I also forgot xcccc

**Comment by MartinMelo97** [comment]
Also, work with this mockup https://user-images.githubusercontent.com/46948948/61095161-ec77fb80-a417-11e9-8dcf-cb813ea69329.png, this is the approved

**Comment by Inatedy** [comment]
fine

**Comment by Inatedy** [comment]
![admin-form](https://user-images.githubusercontent.com/46948948/61095957-5fcf3c80-a41b-11e9-970d-b50771aaa8f3.png)

**Comment by MartinMelo97** [comment]
Yeah! It's great. Approved. Upload it yo Drive pls

**Comment by Inatedy** [comment]
thanks, I´ll upload it
