### ISSUE TITLE
Employee List Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#55]
I remember that it was the last approved mockup for this component: https://user-images.githubusercontent.com/46948948/59858037-cba01700-933f-11e9-94f1-a17ae19dd166.png

But it doesn't appear on Drive folder. Why?

The only change that i could do is hide the Id column. To the admin, the id of the user isn't relevant. And, the width of the search input a little bigger. And it have as placeholder the label "Buscar"

**Comment by Inatedy** [comment]
![LISTVIEW-EMPLOYEE – 1](https://user-images.githubusercontent.com/46948948/60944263-f41b9100-a2ad-11e9-8505-d1fa5d7f0584.png)

**Comment by MartinMelo97** [comment]
Yeah, it's great. Approved. Upload it to mockups folder on Drive pls.
