### ISSUE TITLE
Employee Detail Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#56]
We don't have this mockup done. So we need to design it. We need the info of the employees in this detail, and also see the works and the products related to him.

**Comment by Inatedy** [comment]
![employee-detail](https://user-images.githubusercontent.com/46948948/61093170-de71ad00-a40e-11e9-8b5c-17f40d86e7a5.png)
I can modify this mockup to the model of client detail if you prefer

**Comment by MartinMelo97** [comment]
I like it, I'm going yo Approve ir, but the personal info of the Employee is  #missing. The employee also hace they same info as Admin (First Name, Street, etc). I think that you can do another Mockup. This mockup will be visible when someone scroll down the DOM. And in that mockup you can show the personal info of the Employee.

**Comment by Inatedy** [comment]
@MartinMelo97 sorry, another mockup with the personal info and the status info in the same mockup?

**Comment by Inatedy** [comment]
![Employee Detail Mockup #56 1](https://user-images.githubusercontent.com/46948948/61094825-72934280-a416-11e9-96e1-0561ca42c091.png)
![Employee Detail Mockup #56 2](https://user-images.githubusercontent.com/46948948/61094826-72934280-a416-11e9-8005-bda390ec531e.png)
![admin-form](https://user-images.githubusercontent.com/46948948/61094827-72934280-a416-11e9-9478-35b07c62fcd8.png)
 I modified the version

**Comment by Inatedy** [comment]
or with the last version
![employee-detail](https://user-images.githubusercontent.com/46948948/61094924-f8af8900-a416-11e9-8116-fffd9943c4b5.png)

**Comment by Inatedy** [comment]
@MartinMelo97  Cuáles se aprueban o que les modifico?

**Comment by MartinMelo97** [comment]
Sorry, I didn't see this. 

https://user-images.githubusercontent.com/46948948/61094825-72934280-a416-11e9-96e1-0561ca42c091.png This is the main first page and it's ok, so only remove the photo profile.

https://user-images.githubusercontent.com/46948948/61094826-72934280-a416-11e9-8005-bda390ec531e.png In this show again the name, the username and the edit call to action is redudant. So please remove that info only showing the extra field for the Employee. In works and products, please unify the style of the client detail mockup, with the < > to change the actual producto or work.

**Comment by Inatedy** [comment]
![Employee Detail Mockup #56 -1](https://user-images.githubusercontent.com/46948948/61298447-d82f5800-a7a3-11e9-904f-3015b97e07bd.png)
![Employee Detail Mockup #56 2 – 2](https://user-images.githubusercontent.com/46948948/61298448-d82f5800-a7a3-11e9-9469-9579b8629d54.png)

**Comment by MartinMelo97** [comment]
Yeah, looks perfect, approved. Upload them to Github pls

**Comment by Inatedy** [comment]
vale
