### ISSUE TITLE
Employee Form Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#57]
We need to create the mockup for the form that we're using for create and update an Employee. We need to create a form with the following inputs:

Same as Admin info
Contract vigency (Vigencia del contrato)
Salary (Salario)
Salary Place (Plazo del salario)

**Comment by MartinMelo97** [comment]
We cant make this in two steps. The first step is ask for the personal information, and here we can reuse the Admin Edit Form Mockup. The second step is ask for the aditional information (salary, vigency, etc). And here you only need to create a new mockup with only these fields. What do yo think?

**Comment by Inatedy** [comment]
@MartinMelo97 i like the idea, I´ll wait to the admin edit form

**Comment by Inatedy** [comment]
![Employee Form Mockup #57 -2](https://user-images.githubusercontent.com/46948948/61241537-4f63de00-a709-11e9-9ff1-1ec653ea8942.png)

**Comment by MartinMelo97** [comment]
Approved, upload it to Drive.

**Comment by Inatedy** [comment]
@MartinMelo97  en otra tarea habías mencionado que era redundante que en la siguiente pantalla apareciera de nuevo el nombre por ejemplo uxue, lo quito?

**Comment by MartinMelo97** [comment]
nop, aquí si está bien jeje

**Comment by Inatedy** [comment]
vale
entonces la primer parte queda así?
![Employee Form Mockup #57 -2 – 1 5](https://user-images.githubusercontent.com/46948948/61347781-c392a480-a823-11e9-903e-59177f5577de.png)
![Employee Form Mockup #57 -2 – 1 3](https://user-images.githubusercontent.com/46948948/61347782-c42b3b00-a823-11e9-9ca0-03884ce1a008.png)

**Comment by MartinMelo97** [comment]
Así está

**Comment by Inatedy** [comment]
subo esta primer parte?

**Comment by MartinMelo97** [comment]
Ambas partes

**Comment by Inatedy** [comment]
@martin es este el que faltaba? @martinMelo97

**Comment by Inatedy** [comment]
![Employee Form Mockup #57 -2 – 1 2 – 1](https://user-images.githubusercontent.com/46948948/61412212-e5d10480-a8ad-11e9-8a3f-5f057bb382a5.png)
![Employee Form Mockup #57 -2 – 1 2](https://user-images.githubusercontent.com/46948948/61412213-e5d10480-a8ad-11e9-8f88-e2415252f4f0.png)

**Comment by MartinMelo97** [comment]
Son los dos del comentario que hiciste hace 16 horas que dice "entonces la primera parte queda así?"

**Comment by MartinMelo97** [comment]
Son los dos del comentario que hiciste hace 16 horas que dice "entonces la primera parte queda así?"

**Comment by Inatedy** [comment]
va, ya estan en drive
