### ISSUE TITLE
Client List Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#59]
We can't copy the Employees List Mockup and reuse almost everything in this mockup, the info is exactly the same as the Admin and the Employee. Instead of show "Puesto" and "Fecha de contratación" columns, we can put a "Email", "Teléfono" and "# de trabajos"

**Comment by Inatedy** [comment]
![Client List Mockup #59](https://user-images.githubusercontent.com/46948948/61097290-71ffa980-a420-11e9-8d34-d84004ed1155.png)

**Comment by MartinMelo97** [comment]
Good, approved
