### ISSUE TITLE
Create Mockup for all the data input of the project.

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#6]
We need to create a mockup for each one of the data entries that we will use on the project. The data entries could be:

- Input Text
- Textarea
- Switch
- Date Picker
- Time Picker
- Select
- Multiple Select
- Checkbox
- Radio buttons
- Range

You need to check the Ant Design documentation and search for each type of data entries enum on the top. Attach in this issue a .jpeg and .png image with all the data entries mockup.

**Comment by Inatedy** [comment]
No los, he acabado, pero tenía la duda, si son así ?
![Input-Text – 1](https://user-images.githubusercontent.com/46948948/59432871-ee658500-8dad-11e9-9264-99cf66504d89.png)
![Input-Text](https://user-images.githubusercontent.com/46948948/59432872-ee658500-8dad-11e9-9273-7ac6bcefcd10.png)
![Switch-Area – 1](https://user-images.githubusercontent.com/46948948/59432873-eefe1b80-8dad-11e9-86e2-d59ecca500ed.png)
![Switch-Area – 2](https://user-images.githubusercontent.com/46948948/59432874-eefe1b80-8dad-11e9-9d1c-33f6cef9c23e.png)
![Switch-Area](https://user-images.githubusercontent.com/46948948/59432875-eefe1b80-8dad-11e9-8268-b3dc6e360e27.png)
![Text-area – 1](https://user-images.githubusercontent.com/46948948/59432876-ef96b200-8dad-11e9-98b7-5c7dd248b87a.png)
![Uploading Text-area.png…]()
![Uploading Web 1920 – 1.png…]()

**Comment by Inatedy** [comment]
No los, he acabado, pero tenía la duda, si son así ?
![Input-Text – 1](https://user-images.githubusercontent.com/46948948/59432871-ee658500-8dad-11e9-9264-99cf66504d89.png)
![Input-Text](https://user-images.githubusercontent.com/46948948/59432872-ee658500-8dad-11e9-9273-7ac6bcefcd10.png)
![Switch-Area – 1](https://user-images.githubusercontent.com/46948948/59432873-eefe1b80-8dad-11e9-86e2-d59ecca500ed.png)
![Switch-Area – 2](https://user-images.githubusercontent.com/46948948/59432874-eefe1b80-8dad-11e9-9d1c-33f6cef9c23e.png)
![Switch-Area](https://user-images.githubusercontent.com/46948948/59432875-eefe1b80-8dad-11e9-8268-b3dc6e360e27.png)
![Text-area – 1](https://user-images.githubusercontent.com/46948948/59432876-ef96b200-8dad-11e9-98b7-5c7dd248b87a.png)
![Text-area](https://user-images.githubusercontent.com/46948948/59432879-f0c7df00-8dad-11e9-80d5-050637065935.png)
![Uploading Web 1920 – 1.png…]()

**Comment by Inatedy** [comment]
![Date-picker](https://user-images.githubusercontent.com/46948948/59434597-7a2ce080-8db1-11e9-8dab-0b6511f8b3d0.png)

**Comment by Inatedy** [comment]
![Date-picker – 1](https://user-images.githubusercontent.com/46948948/59463386-7a49d200-8deb-11e9-83f4-6ef856dbb698.png)

**Comment by Inatedy** [comment]
![Date-picker – 1](https://user-images.githubusercontent.com/46948948/59463624-107df800-8dec-11e9-83fd-8f6e4b4bcc65.png)

**Comment by Inatedy** [comment]
![Date-picker – 1](https://user-images.githubusercontent.com/46948948/59463738-491dd180-8dec-11e9-94c5-f2ffdcd075db.png)

**Comment by Inatedy** [comment]
![Select](https://user-images.githubusercontent.com/46948948/59464232-80d94900-8ded-11e9-813d-db5b096d06d9.png)

**Comment by Inatedy** [comment]
![Range](https://user-images.githubusercontent.com/46948948/59466695-92255400-8df3-11e9-9d48-a6ef5c7596b8.png)
![Check-box](https://user-images.githubusercontent.com/46948948/59466696-92255400-8df3-11e9-9c61-0eea6cdecfa3.png)
![Radio-butttons](https://user-images.githubusercontent.com/46948948/59466698-92255400-8df3-11e9-8952-0d4d77cf39a4.png)

**Comment by Inatedy** [comment]
![Multiple-select](https://user-images.githubusercontent.com/46948948/59467478-673bff80-8df5-11e9-8415-47640630e985.png)

**Comment by Inatedy** [comment]
![Input-Text – 22](https://user-images.githubusercontent.com/46948948/59467920-78394080-8df6-11e9-9300-46da7de8c554.png)
![Input-Text – 23](https://user-images.githubusercontent.com/46948948/59467922-78d1d700-8df6-11e9-86fd-e4425505a78b.png)

**Comment by MartinMelo97** [comment]
Input text -> https://user-images.githubusercontent.com/46948948/59467922-78d1d700-8df6-11e9-86fd-e4425505a78b.png

Text area -> https://user-images.githubusercontent.com/46948948/59432879-f0c7df00-8dad-11e9-80d5-050637065935.png

Text area (onHover, onFocus) -> https://user-images.githubusercontent.com/46948948/59432876-ef96b200-8dad-11e9-98b7-5c7dd248b87a.png

Switch -> https://user-images.githubusercontent.com/46948948/59432875-eefe1b80-8dad-11e9-8268-b3dc6e360e27.png

Switch active -> https://user-images.githubusercontent.com/46948948/59432874-eefe1b80-8dad-11e9-9d1c-33f6cef9c23e.png

<=== NOTE: MAYBE IN THE SWITCH TRY WITH THE CIRCLE WITH THE MAIN COLOR ===>

Date Picker: https://user-images.githubusercontent.com/46948948/59434597-7a2ce080-8db1-11e9-8dab-0b6511f8b3d0.png

Time Picker: https://user-images.githubusercontent.com/46948948/59463738-491dd180-8dec-11e9-94c5-f2ffdcd075db.png

Select: https://user-images.githubusercontent.com/46948948/59464232-80d94900-8ded-11e9-813d-db5b096d06d9.png

Select open -> Missed (do a mockup for it)

Multiple seleect -> https://user-images.githubusercontent.com/46948948/59467478-673bff80-8df5-11e9-8415-47640630e985.png

Checkbox ->https://user-images.githubusercontent.com/46948948/59466696-92255400-8df3-11e9-9c61-0eea6cdecfa3.png

Radio button -> https://user-images.githubusercontent.com/46948948/59466698-92255400-8df3-11e9-8952-0d4d77cf39a4.png

Range -> MIssed

This: https://user-images.githubusercontent.com/46948948/59466695-92255400-8df3-11e9-9d48-a6ef5c7596b8.png is a time range. But a range is like: https://ant.design/components/slider/

**Comment by MartinMelo97** [comment]
TO DO: Mockups for:

- Switch using main color
- Select (single and multiple) opened
- Range (Slider in Ant Design

**Comment by Inatedy** [comment]
Okay, I´ll work on it.

**Comment by Inatedy** [comment]
![Range – 2](https://user-images.githubusercontent.com/46948948/59636474-39b6c500-9119-11e9-9750-0569ad1251af.png)
![Select – 1](https://user-images.githubusercontent.com/46948948/59636475-3a4f5b80-9119-11e9-999e-941fc52fd173.png)
![Range – 1](https://user-images.githubusercontent.com/46948948/59636476-3a4f5b80-9119-11e9-8a46-968f09f36fda.png)

**Comment by Inatedy** [comment]
![Switch-Area](https://user-images.githubusercontent.com/46948948/59642363-4bed2f00-912a-11e9-95bf-b74c59153840.png)
![Switch-Area – 3](https://user-images.githubusercontent.com/46948948/59642365-4bed2f00-912a-11e9-88a0-3c3569e23e06.png)
