### ISSUE TITLE
Client Detail Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#60]
We don't have this mockup done. So we need to design it. We need the info of the clients in this detail, and also see the works related to its. We can also reuse the Employee Detail Mockup

**Comment by Inatedy** [comment]
![Client Detail Mockup #60](https://user-images.githubusercontent.com/46948948/61254572-90b8b580-a72a-11e9-90f4-944925ede707.png)
 tuve que juntar personal info con trabajos, tiene un orden diferente y sobra espacio debajo de la foto.
No es el mismo mockup que el de employees debido a la información de contratación y todo eso, cómo ves?
cambia el diseño que ya tenemos para employees, hay más info que agregar para los clientes aparte de la personal????

**Comment by Inatedy** [comment]
![Client Detail Mockup #60](https://user-images.githubusercontent.com/46948948/61255405-0eca8b80-a72e-11e9-8be1-f1d7446e05a7.png)

**Comment by MartinMelo97** [comment]
I like more this version: https://user-images.githubusercontent.com/46948948/61255405-0eca8b80-a72e-11e9-8be1-f1d7446e05a7.png but the Client won't have photo so please remove it.

**Comment by Inatedy** [comment]
![Client Detail Mockup #60 – 1](https://user-images.githubusercontent.com/46948948/61263016-03d32380-a74d-11e9-96cc-66db0ef46ffe.png)

**Comment by MartinMelo97** [comment]
Yep, i like it! Add it to Drive pls.

**Comment by Inatedy** [comment]
ok c:
