### ISSUE TITLE
Client Form Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#61]
We need to create the mockup for the Form for Create and Update a client. The fields that we need to ask for a client are the same personal info for Admin and Employee

**Comment by Inatedy** [comment]
![Client Form Mockup #61 – 1](https://user-images.githubusercontent.com/46948948/61248902-a5408200-a719-11e9-9829-ed1679461f8f.png)
![Client Form Mockup #61](https://user-images.githubusercontent.com/46948948/61248903-a5d91880-a719-11e9-86cf-0d5f43120ed8.png)

**Comment by MartinMelo97** [comment]
Yeah it's the same mockup for admin and employee form. Only the client won't have photo.

**Comment by Inatedy** [comment]
![Client Form Mockup #61 – 1](https://user-images.githubusercontent.com/46948948/61263278-e5215c80-a74d-11e9-9267-be8b4640e889.png)
![Client Form Mockup #61](https://user-images.githubusercontent.com/46948948/61263279-e5b9f300-a74d-11e9-89fb-1590cdfecc67.png)
@MartinMelo97

**Comment by MartinMelo97** [comment]
Approved. Upload both to Drive folder
