### ISSUE TITLE
Service List Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#63]
You did this mockup https://user-images.githubusercontent.com/46948948/59734941-13784e80-9219-11e9-975b-6e3440ffb525.png.
I like it. Only unifique this mockup with the Employee List mockup, (search input, Columns id hidden, etc). Also match with the changes required in the Employee List mockup issue.

**Comment by Inatedy** [comment]
los campos van a ser: nombre, costo, descripción?

**Comment by Inatedy** [comment]
![Service List Mockup #63](https://user-images.githubusercontent.com/46948948/61246691-10d42080-a715-11e9-9dc6-aea81c7014ff.png)

**Comment by MartinMelo97** [comment]
Approved. Upload it to Drive pls.
