### ISSUE TITLE
Service Detail Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#64]
We not a have a mockup for the Detail of a Service. In this mockup we need to show the info about the service. And the works related to this service.

**Comment by Inatedy** [comment]
![Service Detail Mockup #64](https://user-images.githubusercontent.com/46948948/61247160-2269f800-a716-11e9-8fd3-95a6811793a7.png)

**Comment by MartinMelo97** [comment]
Approved. Upload it to Drive
