### ISSUE TITLE
Service Form Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#65]
We need to create a form to create and update a service. The fields that we need to put in the form are:

- Name (Nombre)
- Desc (Descripción)
- Cost (Costo)
- Date Unit (Unidad de tiempo)

**Comment by Inatedy** [comment]
![Service Form Mockup #65](https://user-images.githubusercontent.com/46948948/61248853-922db200-a719-11e9-9f04-8621a759d02c.png)
![Service Form Mockup #65 -1](https://user-images.githubusercontent.com/46948948/61248856-92c64880-a719-11e9-84a5-15d9ba43af28.png)

**Comment by MartinMelo97** [comment]
Instead of "Unidad de tiempo" change it for "Duración"

**Comment by MartinMelo97** [comment]
And replace the select of "Duración" for a input number and another select for the time units (minutos, horas, días, semanas, etc)

**Comment by Inatedy** [comment]
![Service Form Mockup #65](https://user-images.githubusercontent.com/46948948/61253509-e12e1400-a726-11e9-9369-e5ef7fde4388.png)
![Service Form Mockup #65 -1](https://user-images.githubusercontent.com/46948948/61253510-e12e1400-a726-11e9-9ff7-741d1b59f913.png)

**Comment by MartinMelo97** [comment]
Instead of a select for the number, put a input, in the frontend we'll validate the max number

**Comment by Inatedy** [comment]
![Service Form Mockup #65 -1](https://user-images.githubusercontent.com/46948948/61255596-d9726d80-a72e-11e9-9d02-f8d604ad47d5.png)
![Service Form Mockup #65](https://user-images.githubusercontent.com/46948948/61255597-d9726d80-a72e-11e9-9875-47b2c756ff61.png)

**Comment by MartinMelo97** [comment]
Yeah, i like it a lot the "Crear" button will be for the creation, and the "Guardar" for the update. Approved. Upload it to develop.

**Comment by Inatedy** [comment]
yep
