### ISSUE TITLE
Mockup Navbar (or Sidebar)

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#7]
Create mockup designing the navbar. The navbar will have the following links.
- Empleados
- Clientes
- Productos (it will have a submenu called "Almacenes")
- Servicios
- Trabajos
- Contabilidad
- Usuario (it will have a option called "Cerrar Sesión")

Check the Notaría Tula navbar and based on it. On the left (navbar) put the Gosen logo.

=== UPDATE === 
Maybe is a better idea have a sidebar instead of a navbar. Check in Ant Design Docs the sidebar, and make another mockup with the links, but using a sidebar.

Attach navbar and sidebar mockups in this issue in a .png or .jpeg image.

**Comment by Inatedy** [comment]
sidebar

![side-bar – 1](https://user-images.githubusercontent.com/46948948/59558825-db76ce80-8fc0-11e9-847c-f49ece859a5d.png)
![side-bar](https://user-images.githubusercontent.com/46948948/59558826-db76ce80-8fc0-11e9-8335-639792116eb8.png)

**Comment by Inatedy** [comment]
navbar
![nave-bar – 1](https://user-images.githubusercontent.com/46948948/59558968-622cab00-8fc3-11e9-8e8b-5c00aa44f26d.png)
![nave-bar](https://user-images.githubusercontent.com/46948948/59558969-622cab00-8fc3-11e9-86f6-67234f37b78b.png)

**Comment by Inatedy** [comment]
navbar

![nave-bar – 1](https://user-images.githubusercontent.com/46948948/59558976-9c964800-8fc3-11e9-9e1c-41eca9f05529.png)
![nave-bar](https://user-images.githubusercontent.com/46948948/59558977-9c964800-8fc3-11e9-89c0-6d8bc77bb460.png)

**Comment by MartinMelo97** [comment]
@Inatedy I like all, but I think that the sidebar with the icons is the best option. I'll close this issue, but we should looking for others icons. Thank you

**Comment by Inatedy** [comment]
@martin should I looking for others icons? @MartinMelo97 ??
