### ISSUE TITLE
Mockup Footer

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#8]
Create the mockup for the footer of the project. So minimalist, only with "Powered By Actosoft 2019". Attach an image with that mockup in this issue.

**Comment by Inatedy** [comment]
![footer – 1](https://user-images.githubusercontent.com/46948948/59559041-1ed33c00-8fc5-11e9-97d9-cbd760a98a99.png)
![Uploading footer.png…]()

**Comment by Inatedy** [comment]
![footer – 1](https://user-images.githubusercontent.com/46948948/59559064-7b365b80-8fc5-11e9-8cc0-fe5e475fe837.png)
![footer](https://user-images.githubusercontent.com/46948948/59559065-7b365b80-8fc5-11e9-88ba-5fb45450fda9.png)

**Comment by MartinMelo97** [comment]
I liked the footer with the right aligment text. Only if we could have a separator line it could be great. I'll close this issue.
