### ISSUE TITLE
Organize mockups folder on Drive

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#81]
Please into the Gosen/Design/Mockups/Components folder create the following structure

Components
    - Model
        - List Mockup
        - Detail Mockup
        - Create Mockup
        - Update Mockup

Models: Admin, Employee, Client, Services.

**Comment by Inatedy** [comment]
- List Mockup
- Detail Mockup
- Create Mockup
- Update Mockup
esas van a ser las carpetas y dentro de ellas agrego lo de Admin, Employee, Client, Services.? @MartinMelo97

**Comment by MartinMelo97** [comment]
Nono, you should create a folder for each model (Services, Employees, Clients and Admins) and inside each folder you must put there each mockup (list, detail, create, update)

**Comment by Inatedy** [comment]
Vale vale

**Comment by MartinMelo97** [comment]
Missing Employe Create Form Part1 Mockup
