### ISSUE TITLE
Product List Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#84]
I don't remember if you did a mockup for this in past. As product, i think we could design this mockup using card with images. On a grid system, make the card md-4 to have 3 cards in one row. Also make this mockup using the list reusable component that we are using for the other models pls.

**Comment by Inatedy** [comment]
![LISTVIEW-products – 4](https://user-images.githubusercontent.com/46948948/61760378-f7744980-ad90-11e9-9bb0-e24be9bdb9fb.png)
jejej qué modificaciones le hago?? 4 cards por fila,also?

**Comment by Inatedy** [comment]
![Product List Mockup #84 list](https://user-images.githubusercontent.com/46948948/61762014-2f31c000-ad96-11e9-9fcb-d3d0d5ce026d.png)
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/61762015-2f31c000-ad96-11e9-94db-380135fb62f3.png)

**Comment by Inatedy** [comment]
@MartinMelo97 Qué modificaciones les aplico?

**Comment by MartinMelo97** [comment]
The card maybe 4 in a row, i think that it seems a little bigger

**Comment by Inatedy** [comment]
yep, a lot

**Comment by Inatedy** [comment]
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/61805624-ba916c80-adfb-11e9-93dd-54bf82c3c06e.png)
@MartinMelo97

**Comment by MartinMelo97** [comment]
Yeah it s good, but can you make the card a little small? The idea is have more spacing between the cards

**Comment by Inatedy** [comment]
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/61807607-7bfdb100-adff-11e9-93cb-1dc7eecf5d2c.png)
@MartinMelo97

**Comment by MartinMelo97** [comment]
Ok ok, me gusta un poco más así. Sólo en donde va el nombre del producto, quitar el número que tiene del lado izquierdo.

**Comment by MartinMelo97** [comment]
@Inatedy Pls para cerrar este issue

**Comment by MartinMelo97** [comment]
@Inatedy je

**Comment by Inatedy** [comment]
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/62399280-e8378d80-b540-11e9-8a39-e7a7b96729d8.png)

**Comment by MartinMelo97** [comment]
Ok thats, great only let a little space between the first row of card and the "Productos, Ordenar por, Buscar" options.

**Comment by Inatedy** [comment]
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/62401123-7ca4ee80-b547-11e9-8a9a-73e6eb3112e1.png)

**Comment by Inatedy** [comment]
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/62401235-ede4a180-b547-11e9-954c-de6eb6970ddc.png)

**Comment by MartinMelo97** [comment]
A little more.

**Comment by Inatedy** [comment]
![Product List Mockup #84 card](https://user-images.githubusercontent.com/46948948/62401849-7ebc7c80-b54a-11e9-9d31-8033d4f7bccb.png)

**Comment by MartinMelo97** [comment]
OK. Upload it to Drive.

**Comment by Inatedy** [comment]
ok
