### ISSUE TITLE
Product Detail Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#85]
I like to see in the detail product the next info:
- Código de barras (numbers)
- Nombre
- Descripción
- Imágenes del producto (0 to N images per product)
- Existencias (We have stocks (almacenes), so in each stock they could have X qty of this product. So we have to show all the stock where this product exists and the number of pieces)

**Comment by Inatedy** [comment]
![Product Detail Mockup #85](https://user-images.githubusercontent.com/46948948/61805571-a51c4280-adfb-11e9-8fa0-29bdeb969446.png)
![Product Detail Mockup #85 add image](https://user-images.githubusercontent.com/46948948/61805572-a51c4280-adfb-11e9-8a68-a74d60f8db74.png)
![Product Detail Mockup #85 versión 2](https://user-images.githubusercontent.com/46948948/61805575-a5b4d900-adfb-11e9-92ef-c049507956e0.png)

**Comment by MartinMelo97** [comment]
The last one, with the Almacen cards below the main info of the product.

**Comment by Inatedy** [comment]
ok, I add the version without photo
![Product Detail Mockup #85 versión 2 – 1](https://user-images.githubusercontent.com/46948948/61813481-65f5ed80-ae0b-11e9-8c11-b682274e824f.png)

**Comment by MartinMelo97** [comment]
Muy bieeeen

**Comment by MartinMelo97** [comment]
Upload it to Drive pls.
