### ISSUE TITLE
Product Create/Edit Form Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#86]
We need to create the mockup for form of creation/update of a product.

*This will be a 3 parts form*
1º part:
Inputs:
- Barcode
- Name*
- Description

2º part:
- (Only in edit form) See the actual images uploaded for this product (if it have). The user can deleted those images.
- (On Create and Edit) Upload image button (File input)

3º part:
- (Only in edit form) See the stocks where exists pieces of this product (if it have). The user can modify the quantity or delete this product for a specific stock.
- (On Create and Edit): Select with all the active stocks. Numeric Input to set the qty of pieces of this product. Label "Crear nuevo almacen"

If you have any doubt, please ask me.

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/61816744-9ab97300-ae12-11e9-9346-948ccd796054.png)
![Uploading Product Edit Form Mockup #86 – 1.png…]()
tengo duda de que boton se queda para agregar almacen

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/61816744-9ab97300-ae12-11e9-9346-948ccd796054.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61816745-9ab97300-ae12-11e9-9f6e-508d4893f826.png)
tengo duda de que boton se queda para agregar almacen

**Comment by MartinMelo97** [comment]
https://user-images.githubusercontent.com/46948948/61816745-9ab97300-ae12-11e9-9f6e-508d4893f826.png This Button for "Agregar almacén" it's perfect. Only make the create mockup bases on this

**Comment by MartinMelo97** [comment]
Only in the images, i like to see (only in form) allí te images and don't have to click in left or right arrow to change they image. Can se try put fue imagen on a vertical column?

**Comment by Inatedy** [comment]
in vertical column 1, and if are more of 1, should I make smaller the images or with the slider? @MartinMelo97

**Comment by MartinMelo97** [comment]
Todas las imágenes apiladas verticalmente, una arriba de otra y así jeje

**Comment by MartinMelo97** [comment]
Si hay dos y se agrega otra, iría debajo de esas 2, me gustaría que la columna estuviera del lado derecho

**Comment by Inatedy** [comment]
oooooohhh dejame ver si entendí

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/61818066-9a6ea700-ae15-11e9-8b66-8d80904310dd.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61818067-9b073d80-ae15-11e9-996f-7a5c7a6cde17.png)

**Comment by MartinMelo97** [comment]
![IMG_20190724_133449](https://user-images.githubusercontent.com/6130385/61819104-f0444e80-ae17-11e9-9f11-797d3c3d4c7b.jpg)

**Comment by MartinMelo97** [comment]
Something like this

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61819773-4b2a7580-ae19-11e9-9426-7f42ea12b480.png)

**Comment by MartinMelo97** [comment]
Podríamos intentar que la parte de las imágenes sea una parte independiente a donde está la información del producto? Que este en otro div negro y que abarque toda la altura del mockup?

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61824102-cd6b6780-ae22-11e9-866a-d19bc6d1d971.png)

**Comment by MartinMelo97** [comment]
Me gusto más este https://user-images.githubusercontent.com/46948948/61819773-4b2a7580-ae19-11e9-9426-7f42ea12b480.png. Sólo ponle una barrita de que se puede hacer scroll verticalmente y ver si se le puede agregar una leyenda al botón de + como "Agregar imagen".

Igual me gustaría ver el mismo mockup, pero cuando aún no se agregan imágenes

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/61824976-f5f46100-ae24-11e9-8bfe-eaeb4a5f2cb3.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61824978-f5f46100-ae24-11e9-96f4-d910cf11e136.png)

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/61825022-12909900-ae25-11e9-9ad9-4a811b17f65c.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61825023-13292f80-ae25-11e9-9a2f-23228f4d5760.png)

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/61825322-bd08bc00-ae25-11e9-9c58-50c61a9fa7c7.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61825325-bda15280-ae25-11e9-91a1-094183ff9885.png)

**Comment by MartinMelo97** [comment]
https://user-images.githubusercontent.com/46948948/61824976-f5f46100-ae24-11e9-8bfe-eaeb4a5f2cb3.png *Este para cuando no hay imágenes*

https://user-images.githubusercontent.com/46948948/61825023-13292f80-ae25-11e9-9a2f-23228f4d5760.png *Este para cuando ya hay imágenes*

Sólo en donde dice "Almacen" debería decir "Almacenes" y yo creo que igual los almacenes, en lugar de tener flechas, vamos a colocarles un scroll horizontal

**Comment by Inatedy** [comment]
@MartinMelo97 hago estas modificaciones del scroll y de las imagenes a la derecha para los demás mockups de este sprint?

**Comment by MartinMelo97** [comment]
Mmm
Por el momento sólo para este

**Comment by MartinMelo97** [comment]
Porque creo sólo productos lleva imagen

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/61837176-2a7a1400-ae49-11e9-9326-d9c7b5821f2c.png)
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/61837177-2b12aa80-ae49-11e9-9588-e178f23d796e.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61837179-2bab4100-ae49-11e9-8024-f79a730936be.png)

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/61837266-9eb4b780-ae49-11e9-8d88-d93f113594f7.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61837267-9f4d4e00-ae49-11e9-93df-f91883e32996.png)
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/61837268-9fe5e480-ae49-11e9-98ce-92dd5c3dd185.png)

**Comment by MartinMelo97** [comment]
Cuando ya hay almacenes vinculados con este producto, debería de seguir apareciendo el select de almacenes, con los almacenes donde no existe el producto.

**Comment by Inatedy** [comment]
@MartinMelo97  en edit?

**Comment by MartinMelo97** [comment]
Chi

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/61909486-e6921800-aef7-11e9-82bc-99375f48a7ec.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61909487-e6921800-aef7-11e9-85b3-ad3379b12ecf.png)

**Comment by MartinMelo97** [comment]
Solo veamos cómo se pone si el de "Agregar almacén" queda hasta la derecha, quedando:
Select - Almacenes ya - Agregar almacenes

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/61909834-b8f99e80-aef8-11e9-803c-7cddf0bd7149.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61909836-b8f99e80-aef8-11e9-89fc-57a3d6eb10e4.png)

**Comment by MartinMelo97** [comment]
Mejor, ahora solo ajusta el width para que tenga correspondencia lo que está arriba con lo que está abajo. Es decir que el doc dónde está la info del producto termine donde termina el de almacén. Y que donde están las imágenes tenga el mismo width que el botón de "Agregar almacén"

**Comment by Inatedy** [comment]
@MartinMelo97 el cuaro negro de la info del producto lo hago entonces más grande?

**Comment by MartinMelo97** [comment]
Si para que cuadre

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/61915874-ee5bb780-af0b-11e9-83ea-27d069b11a98.png)

**Comment by Inatedy** [comment]
@MartinMelo97 ayer segun yo lo había enviado, pero no le aprete el botón de Comment jajja

**Comment by MartinMelo97** [comment]
Sorry, no había visto esto. Está bien sólo que todo lo de las imágenes tiene que cuadrar con el botón de "Agregar almacén". Es decir, lo de las imágenes tiene que tener el mismo width que es botón, para que se vea la proporcionalidad

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/62012048-b68c8400-b146-11e9-8681-9fc110f34071.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/62012049-b7251a80-b146-11e9-9a75-57ddec1d7830.png)
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/62012050-b7251a80-b146-11e9-9ad5-4a763ec93e63.png)

**Comment by MartinMelo97** [comment]
Justo así! Súbelos a Drive por favor, tendrían que ser 4:
- Crear sin imágenes
- Crear con imágenes
- Editar sin imágenes
- Editar con imágenes

**Comment by Inatedy** [comment]
El que subí es crear con o sin imagen? @MartinMelo97

**Comment by Inatedy** [comment]
![Product Create Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/62012561-944a3480-b14d-11e9-8aa4-df6830205342.png)
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/62012562-94e2cb00-b14d-11e9-94c9-a586f5338930.png)
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/62012563-94e2cb00-b14d-11e9-9e52-9ca8f18413fc.png)
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/62012564-957b6180-b14d-11e9-837f-3bf8fd23bef5.png)

**Comment by MartinMelo97** [comment]
Así mero

**Comment by Inatedy** [comment]
va, los subo? @MartinMelo97

**Comment by MartinMelo97** [comment]
Sólo el select de "Almacenes" que quede justo en medio verticalmente hablando

**Comment by Inatedy** [comment]
![Product Edit Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/62399196-968f0300-b540-11e9-8a84-40e796a0e4ac.png)
![Product Create Form Mockup #86 – 1](https://user-images.githubusercontent.com/46948948/62399197-968f0300-b540-11e9-9736-f650961136e2.png)
![Product Edit Form Mockup #86 – 2](https://user-images.githubusercontent.com/46948948/62399198-968f0300-b540-11e9-92d0-f7168c07ec22.png)
![Product Create Form Mockup #86](https://user-images.githubusercontent.com/46948948/62399199-968f0300-b540-11e9-8f04-d2ec46153044.png)

**Comment by MartinMelo97** [comment]
Ok! Upload it to Drive.

**Comment by Inatedy** [comment]
ok
