### ISSUE TITLE
Mockup Modal Confirm for actions.

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#9]
In this project, we're going to add some style to the confirm actions. So we're going to build a modal to confirm some actions (i.e. delete something). Check about this in Ant Design Docs in the Modal part. Attach the mockup as image in this issue.

**Comment by Inatedy** [comment]
![nave-bar – 2](https://user-images.githubusercontent.com/46948948/59559228-54c5ef80-8fc8-11e9-8847-f5b5ffef78af.png)
![nave-bar – 3](https://user-images.githubusercontent.com/46948948/59559229-54c5ef80-8fc8-11e9-805e-636c8a6689e5.png)

**Comment by Inatedy** [comment]
![nave-bar – 3](https://user-images.githubusercontent.com/46948948/59559245-935baa00-8fc8-11e9-85b3-bdfb388e2f9f.png)
![nave-bar – 2](https://user-images.githubusercontent.com/46948948/59559246-935baa00-8fc8-11e9-8605-cb8d08d66e36.png)

**Comment by Inatedy** [comment]
![nave-bar – 3](https://user-images.githubusercontent.com/46948948/59559254-cd2cb080-8fc8-11e9-8025-667915593de0.png)
![nave-bar – 2](https://user-images.githubusercontent.com/46948948/59559256-cdc54700-8fc8-11e9-969c-dc3a034a8775.png)

**Comment by Inatedy** [comment]
![nave-bar – 4](https://user-images.githubusercontent.com/46948948/59559271-1250e280-8fc9-11e9-863d-421c040c1cd0.png)
![nave-bar – 5](https://user-images.githubusercontent.com/46948948/59559272-12e97900-8fc9-11e9-81cd-9ebc7b8b2a3b.png)

**Comment by MartinMelo97** [comment]
@Inatedy I liked the modal with the primary color text. It look great, only if the action is warning (i.e. a delete of some product) the "Borrar" text could be in a red color.
