### ISSUE TITLE
Stock List Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#91]
Continue using the list reusable mockup as the other models.
*Columns*:
Nombre
Ubicación
Acciones

**Comment by Inatedy** [comment]
@MartinMelo97 en acciones que le pongo???

**Comment by MartinMelo97** [comment]
Editar y eliminar

**Comment by Inatedy** [comment]
![Stock List Mockup #91](https://user-images.githubusercontent.com/46948948/62401348-76634200-b548-11e9-8feb-c62ef4965831.png)

**Comment by MartinMelo97** [comment]
Así de sencillito, sólo que no tenga lo del Almacén antes del nombre pls

**Comment by Inatedy** [comment]
![Stock List Mockup #91](https://user-images.githubusercontent.com/46948948/62401770-4321b280-b54a-11e9-9a84-ef580bad519b.png)

**Comment by MartinMelo97** [comment]
OK. Upload it to Drive.

**Comment by Inatedy** [comment]
ok
