### ISSUE TITLE
Stock Detail Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#92]
On this detail we need to show the basic info of a stock (Name, Address, Description) and show the products storage in that stock. For each product we need to show one image, the name and the quantity in that stock

**Comment by Inatedy** [comment]
![Stock Detail Mockup #92 – 2](https://user-images.githubusercontent.com/46948948/62400622-7b72c200-b545-11e9-8990-9c4dff219261.png)
![Stock Detail Mockup #92 – 1](https://user-images.githubusercontent.com/46948948/62400623-7c0b5880-b545-11e9-9ca7-939efc33ac90.png)
![Stock Detail Mockup #92](https://user-images.githubusercontent.com/46948948/62400625-7c0b5880-b545-11e9-816d-7b4499d9109f.png)
![Stock Detail Mockup #92 – 3](https://user-images.githubusercontent.com/46948948/62400626-7c0b5880-b545-11e9-9543-344b24f445f2.png)

**Comment by MartinMelo97** [comment]
https://user-images.githubusercontent.com/46948948/62400623-7c0b5880-b545-11e9-9ca7-939efc33ac90.png I like this. Maybe we can add a option to add a product right here.

**Comment by Inatedy** [comment]
![Stock Detail Mockup #92 – 1](https://user-images.githubusercontent.com/46948948/62401626-a4955180-b549-11e9-8150-c0eb200ded93.png)

**Comment by MartinMelo97** [comment]
Muy bien! Aunque debería tener una opción para los productos que sea "Ver todos"

**Comment by MartinMelo97** [comment]
Porque si son 100 productos, va a querer consultar rápidamente alguno de ellos. Entonces agrégale un link que lo mande a otra URL

**Comment by Inatedy** [comment]
![Stock Detail Mockup #92 – 1](https://user-images.githubusercontent.com/46948948/62402521-c1cc1f00-b54d-11e9-8183-536ccc8b7dc9.png)
![Stock Detail Mockup #92 – 2](https://user-images.githubusercontent.com/46948948/62402522-c264b580-b54d-11e9-950d-e2d27944279d.png)

**Comment by MartinMelo97** [comment]
Perfecto. Per con 4 por fila pls

**Comment by Inatedy** [comment]
![Stock Detail Mockup #92 – 2](https://user-images.githubusercontent.com/46948948/62402679-7fefa880-b54e-11e9-9828-d8195bf382ff.png)

**Comment by MartinMelo97** [comment]
Mucho mejor. Upload it to Drive.
