### ISSUE TITLE
Stock Form Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#93]
Create the form to create or edit a stock. The form need to handle the basic info of a stock (Name, Address, Description) and the feature to add existing products to this stock. We could have a select with the existing products and set the number of pieces existing.

**Comment by Inatedy** [comment]
![Stock Edit-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62404834-58eca300-b55d-11e9-8850-60b69b8ac237.png)
![Stock Create-Form Mockup #93 – 1](https://user-images.githubusercontent.com/46948948/62404835-58eca300-b55d-11e9-8a33-c31a5d571259.png)
![Stock Create-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62404836-59853980-b55d-11e9-8e90-9d2b8ceb88ae.png)

**Comment by MartinMelo97** [comment]
https://user-images.githubusercontent.com/46948948/62404835-58eca300-b55d-11e9-8a33-c31a5d571259.png Está bien este, solo queos productos agregados se ven un poco más visibles, tal vez como cards chiquitas. E indicar que el select de números es para especificar la cantidad

**Comment by Inatedy** [comment]
![Stock Create-Form Mockup #93 – 1](https://user-images.githubusercontent.com/46948948/62405417-9869be00-b562-11e9-986f-57b1733731a4.png)
![Stock Create-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62405418-9869be00-b562-11e9-87b2-546120a0cb6b.png)
![Stock Edit-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62405419-99025480-b562-11e9-8e7f-8eaf8d811ea2.png)

**Comment by MartinMelo97** [comment]
Podríamos intentar poner en cada producto su imagen?

**Comment by Inatedy** [comment]
sippp

**Comment by Inatedy** [comment]
![Stock Create-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62405687-124f7680-b566-11e9-940e-265da5b475f7.png)
![Stock Edit-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62405688-124f7680-b566-11e9-9597-2576210f1065.png)
![Stock Create-Form Mockup #93 – 1](https://user-images.githubusercontent.com/46948948/62405689-124f7680-b566-11e9-9d06-d714615e4a11.png)

**Comment by MartinMelo97** [comment]
Maybe make the image a little small

**Comment by Inatedy** [comment]
![Stock Create-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62499155-3ea60580-b7a7-11e9-9f74-c89536520f3c.png)
![Stock Edit-Form Mockup #93](https://user-images.githubusercontent.com/46948948/62499156-3ea60580-b7a7-11e9-93a1-72b6fd4e8baa.png)
![Stock Create-Form Mockup #93 – 1](https://user-images.githubusercontent.com/46948948/62499157-3f3e9c00-b7a7-11e9-94f7-cb2355efcf11.png)

**Comment by MartinMelo97** [comment]
Yep! Thats it, Upload it to Drive. pls
