### ISSUE TITLE
Work List Mockup.

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#95]
I remember that you made a mockup for this. The list need to have the following columns:
- Servicio (Nombre del servicio que se prestó)
- Empleado (Nombre del empleado que lo hizo)
- Cliente (Nombre del cliente al que se le hizo el servicio)
- Status (Pendiente, En Proceso, Terminado)
- Acciones

**Comment by Inatedy** [comment]
![LISTVIEW-works – 8](https://user-images.githubusercontent.com/46948948/62404927-360ebe80-b55e-11e9-8330-0273566bb4e6.png)
![LISTVIEW-works – 7](https://user-images.githubusercontent.com/46948948/62404928-360ebe80-b55e-11e9-954b-471424bb46ed.png)
![LISTVIEW-works – 6](https://user-images.githubusercontent.com/46948948/62404929-360ebe80-b55e-11e9-86b5-0fd6709edb99.png)
 true tengo estos, ahorita los corrigo

**Comment by MartinMelo97** [comment]
Vale

**Comment by Inatedy** [comment]
![Work List Mockup  #95](https://user-images.githubusercontent.com/46948948/62405781-673fbc80-b567-11e9-8c93-46b060d301cc.png)

**Comment by MartinMelo97** [comment]
Great, only in status i like to see color instead of text

**Comment by Inatedy** [comment]
![Work List Mockup  #95](https://user-images.githubusercontent.com/46948948/62498265-41532b80-b7a4-11e9-8914-46ecb3a6b334.png)

**Comment by MartinMelo97** [comment]
Yeah, upload it to Drive pls.
