### ISSUE TITLE
Work Detail Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#96]
In this mockup we need to show all the info about the work.

Main info (this info need to be the more big and attractive) Service, Client, Status
Pre-main info (below of main info, regular size) Employee(s), Date Start, Date End
Payment info (i like to see it as a sidebar) Total, Payed, to_pay, Option to add transaction.

**Comment by MartinMelo97** [comment]
![Example Sidebar Payment Info](https://user-images.githubusercontent.com/6130385/61906493-14279300-aef1-11e9-87e7-cf3bbc930cc9.jpg)
This is a quickly example about the payment method sidebar

**Comment by Inatedy** [comment]
![Work Detail Mockup #96 – 1](https://user-images.githubusercontent.com/46948948/62407399-ad077f80-b57d-11e9-8fac-b690e9d2c7b6.png)
![Work Detail Mockup #96](https://user-images.githubusercontent.com/46948948/62407401-ada01600-b57d-11e9-9f16-d90b4a80dc98.png)
thanks for the example, really help me

**Comment by Inatedy** [comment]
![Work Detail Mockup #96 – 1](https://user-images.githubusercontent.com/46948948/62407436-20a98c80-b57e-11e9-8791-3f53aa10da63.png)
![Work Detail Mockup #96](https://user-images.githubusercontent.com/46948948/62407437-20a98c80-b57e-11e9-8c65-0ec7ebab8d64.png)
thanks for the example, it really help me

**Comment by Inatedy** [comment]
![Work Detail Mockup #96](https://user-images.githubusercontent.com/46948948/62407448-4d5da400-b57e-11e9-8bde-e82c9fd87d44.png)
![Work Detail Mockup #96 – 1](https://user-images.githubusercontent.com/46948948/62407449-4df63a80-b57e-11e9-8e24-7dc988d44fcb.png)
thanks for the example, it really help me

**Comment by MartinMelo97** [comment]
Perfect, only a little changes:
- El nombre de servicio y de cliente que queden hasta arriba, en la primer fila de arriba hacia abajo.
- Podemos jugar con el status poniendo un tipo semáforo y que esté coloreado el color dependiendo del status, eso lo podemos poner de manera muy minimalista en la esquina superior derecha de la sección de información (no de la de pago). Intentemos con el semáforo y la otra es solo poner un circulito con el color del estado.
- El empleado me gustaría que quedara en la segunda fila. Arriba de las fechas de inicio y termino.
- En las fechas podemos intentar en lugar de ponerla como texto, poner un calendario y marcar el día dependiendo.
- En el botón cuando se va a agregar un campo que diga "Guardar" en lugar de "Realizar"
-

**Comment by Inatedy** [comment]
![Work Detail Mockup #96](https://user-images.githubusercontent.com/46948948/62413855-9db61f80-b5d9-11e9-9a17-dcc324a157aa.png)
![Work Detail Mockup #96 – 1](https://user-images.githubusercontent.com/46948948/62413856-9db61f80-b5d9-11e9-8a6b-a5456e4bcc74.png)

**Comment by Inatedy** [comment]
![Work Detail Mockup #96](https://user-images.githubusercontent.com/46948948/62413883-38aef980-b5da-11e9-8b8c-c5dd6b71e80b.png)

**Comment by MartinMelo97** [comment]
https://user-images.githubusercontent.com/46948948/62413855-9db61f80-b5d9-11e9-9a17-dcc324a157aa.png This style of dates área great. Upload Create and Update to Drive.

**Comment by Inatedy** [comment]
![Work Detail Mockup #96 – 1](https://user-images.githubusercontent.com/46948948/62497995-52e80380-b7a3-11e9-9355-12af111a68a6.png)
![Work Detail Mockup #96](https://user-images.githubusercontent.com/46948948/62497997-53809a00-b7a3-11e9-925d-0b8ec0f4580e.png)
that's how they are.
This issue if for the detail. I´m confused

**Comment by MartinMelo97** [comment]
Sorry, my mistake hahaha. Upload both mockups to Drive pls.
