### ISSUE TITLE
Work Form Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/Gosen-Frontend#97]
The form to create or edit a work need to have the following:

Cliente -> Select with all the clients registered
Servicio -> Select with all the services available
Empleados -> Multiple Select with all the employees available
Fecha de inicio -> Datepicker
Fecha de finalización -> Datepicker
Duración del servicio -> Two Inputs
- Cantidad -> Numeric Input
- Unidad de duración -> Input text (Disable) (When a service is selected, this input filled automatic)

Total -> Numeric Input (When a service and the quantity are filled, this field is calculate)
Anticipo -> Numeric Input

**Comment by Inatedy** [comment]
![Work Edit-Form Mockup #97 – 1](https://user-images.githubusercontent.com/46948948/62502642-225d9500-b7b6-11e9-90b9-88eca586a724.png)
![Work Create-Form Mockup #97](https://user-images.githubusercontent.com/46948948/62502643-22f62b80-b7b6-11e9-8d56-0a09cbfcb3dd.png)

**Comment by MartinMelo97** [comment]
Yeah, I don't see the "Crear/Guardar" button.

**Comment by Inatedy** [comment]
ay no ma!  me pase jajja, sorry xdxd

**Comment by Inatedy** [comment]
![Work Edit-Form Mockup #97 – 1](https://user-images.githubusercontent.com/46948948/62670028-53c19680-b957-11e9-8174-25e42778b9e3.png)
![Work Create-Form Mockup #97](https://user-images.githubusercontent.com/46948948/62670029-53c19680-b957-11e9-852e-2aa72f899c1c.png)
